### ISSUE TITLE
How to get selected coordinates and address?

### ISSUE THREAD

**Issue by giorgio79** [WissamALSbenaty/Ultra-Map-Place-Picker#1]
Hello,

Could you please add to the example how to get the coordinates that the user selected and the address returned by Google (or Huawei? )

**Comment by WissamALSbenaty** [comment]
Hi @giorgio79 
Thanks for asking 

you have two options to get the coordinates :

1- `onCameraMove` callback : it gives you the direct access on the coordinates of the middle of the camera , which is in our situation the selected location

2- if you are using `selectedPlaceWidgetBuilder` callback : you can use `PickResultModel? selectedPlace`, it has an instance of `Geometry` class  which contains the location

Hope this is what you are looking for

**Comment by giorgio79** [comment]
Thank you so much. Perfect :)
