### ISSUE TITLE
Questions about features (Hiding map/nearby locations/radius)

### ISSUE THREAD

**Issue by tiltmaster** [WissamALSbenaty/Ultra-Map-Place-Picker#3]
So I wanted to know if this package supports filtering with range Radius, and if possible to turn off the Map and or Make sure the map is only for viewing purposes, and shows a list of nearby locations based on radius?

**Comment by WissamALSbenaty** [comment]
For making widget just for viewing purposes , unfortunately i didn't include that type of thumbnails , it could be added easily

but for the nearby locations based on radius , i didn't get , could you please provide a UI example for your usecase ?

Thanks

**Comment by tiltmaster** [comment]
> For making widget just for viewing purposes , unfortunately i didn't include that type of thumbnails , it could be added easily
> 
> but for the nearby locations based on radius , i didn't get , could you please provide a UI example for your usecase ?
> 
> Thanks

Hey, I'll try to provide a UI example, its basically the same map and everything, you just cant move the pin to a different location thats all and or just Hide the map and only show a List of nearby places based on Radius like 10 KM radius etc,
