### ISSUE TITLE
Searching Does not return 

### ISSUE THREAD

**Issue by tiltmaster** [WissamALSbenaty/Ultra-Map-Place-Picker#5]
Hi, 

so using the latest update, Searching anything, Does not return any results, while the word "Searching and circular loading show up briefly", no results are returned, and no error is being returned as well. so I am not sure what is going on.

anything changed on that side?

**Comment by tiltmaster** [comment]
Removing StrtictBounds makes the search show up. this might be worth looking into?

**Comment by WissamALSbenaty** [comment]
@tiltmaster 
Hi and sorry for late reponse

It could be changed because of that parameter, i
Changed something related to that widget but i didnt mean to change searching

I will check it ASAP

Thanks for reporting

**Comment by WissamALSbenaty** [comment]
I have checked , there is no changes related to that parameter
