### ISSUE TITLE
Customize style

### ISSUE THREAD

**Issue by YSDC** [WissamALSbenaty/Ultra-Map-Place-Picker#6]
Is there any plan to let us customize the style (color, font, etc.)? This would be really useful, I don't understand why we cannot do it in any place picker lib in Flutter...

**Comment by WissamALSbenaty** [comment]
@YSDC 
Hi there

Could you tell me please what are the widgets that you want to customize?

The library provides builders for pin and the search result widget,

If you look at the docs you will find 2 different UI one of them is the standered UI and the other one is customized 

Thanks for reporting
